export const Countries: string[] = [
  'Nigeria',
  'Ghana',
  'Kenya',
  'South Africa',
  'United States',
  'Egypt',
  'Morocco',
  'Algeria',
  'Ethiopia',
  'Tanzania',
  'Uganda',
  'Rwanda',
  'Senegal',
  'Cameroon',
  'Ivory Coast',
  'Zimbabwe',
  'Zambia',
  'Botswana',
  'Namibia',
  'Mozambique',
  'Madagascar',
  'Tunisia',
  'Libya',
  'Sudan',
  'Angola',
  'Democratic Republic of the Congo',
  'Somalia',
  'Mauritius',
  'Seychelles',
  'Cape Verde',
  'Gambia',
  'Burkina Faso',
  'Mali',
  'Niger',
  'Chad',
  'Malawi',
  'Eswatini',
  'Lesotho',
  'Djibouti',
  'Eritrea',
  'Central African Republic',
  'Equatorial Guinea',
  'Gabon',
  'Sao Tome and Principe',
  'Comoros',
  'Israel',
  'Jordan',
  'Lebanon',
  'Syria',
  'Saudi Arabia',
  'Yemen',
  'Oman',
  'United Arab Emirates',
  'Qatar',
  'Kuwait',
  'Bahrain'
];

export const  States: string[] = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno', 'Cross River', 
  'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 
  'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 
  'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara', 'FCT (Abuja)'
]; // List of Nigerian states